### ISSUE TITLE
OverlayPanel: add `toggleSpeed`

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10499]
### Description

`p:panel` has `closeSpeed` and  `toggleSpeed`. 

Please provide at least `toggleSpeed` to `p:overlayPanel`. Currently, `p:overlayPanel` does always a transition (e.g. from opening to closing with multiple classes `.ui-connected-overlay-enter-active`, `.ui-connected-overlay-exit-active`, etc. which does some transition-effects with opacity.). 

### Describe the solution you would like

I simply want to open **and** close it without any transition, effects and delay. Therefore, a `p:overlayPanel toogleSpeed=0` should disable all animation and transition-effects.

**Comment by melloware** [comment]
Can't use toggleSpeed as you mentioned this is done with animation CSS.  If you want to disable the animation just add this CSS.

```css
.ui-connected-overlay-enter {
    transform: scaleY(1)
}

.ui-connected-overlay-enter-active {
    transition: transform .01s cubic-bezier(0,0,0.2,1),opacity .01s cubic-bezier(0,0,0.2,1)
}

.ui-connected-overlay-exit-active {
    transition: opacity .01s linear
}
```
