### ISSUE TITLE
SplitButton: no right side border radius when no items

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#11155]
There is no border radius on the right side of the button when there are no items:

```xhtml
<p:splitButton value="TODO Checked in"/>
```

<img width="163" alt="Screenshot 2023-12-20 at 11 08 41" src="https://github.com/primefaces/primefaces/assets/7500178/250a08c6-6dbb-41b1-a49e-32838ac84002">

**Comment by jepsar** [comment]
We might need to throw in a CSS class indicating that there is no dropdown button first.

**Comment by melloware** [comment]
@jepsar want me to assign this to you?

**Comment by jepsar** [comment]
It can be done with CSS only. So a workaround is possible.

Current:
```css
body .ui-splitbutton .ui-button:first-child {
    position: relative;
    margin: 0;
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```
Workaround:
```css
html body .ui-splitbutton .ui-button:first-child {
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
}
html body .ui-splitbutton .ui-button:last-child {
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
}
```
