### ISSUE TITLE
TabMenu: badge out of view

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11182]
see the rot dot, firefox:
https://www.primefaces.org/showcase/ui/menu/tabMenu.xhtml?i=1&jfwid=c48e0

**Comment by melloware** [comment]
Yep @jepsar fixed it in main the showcase and in 13.0.4 just waiting on PrimeTek to deploy the 13.0.4 showcase.

**Comment by melloware** [comment]
Oh wait I just tried it locally and it still broken.  @jepsar i thought you fixed this?

**Comment by jepsar** [comment]
Workaround:
```css
html body .ui-tabmenu .ui-tabmenu-nav {
    margin: -.5rem 0 0 0;
    padding: .5rem 0 0 0;
}
```
