### ISSUE TITLE
DataTable: ARIA roles on table elements

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#11504]
### Description

The ARIA roles for `<table>` and `<td>` are overwritten for the DataTable component.
```
<table role="grid"> (implicit "table")
<td role="gridcell"> (implicit "cell")
```
See on [Primefaces Showcase](https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml)
![2024-02-22 16_50_33-DevTools - www primefaces org_showcase_ui_data_datatable_basic xhtml_jfwid=11e28](https://github.com/primefaces/primefaces/assets/6900303/a3c6079b-bc5e-4375-8cf7-d9dec3ccaeb2)

Is there a reason why this is done?

### Describe the solution you would like

Remove the ARIA roles on `<table>` and `<td>` and use the implicit defaults.

**Comment by melloware** [comment]
It looks like a bunch of custom CSS for `reflow` mode was using it to distinguish grid cells from other `td` like if components in the table were using `tr` or `td` like a PanelGrid inside a cell.

**Example:** 
```css
/** Reflow **/
.ui-datatable-reflow .ui-datatable-data td[role="gridcell"] .ui-column-title,
.ui-datatable-reflow .ui-expanded-row-content td .ui-column-title {
    display: none;
}

```
