### ISSUE TITLE
Themes: Style select elements

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#11681]
They are used in the rows per page selector of the DataTable and the navigator of the DatePicker for example. They could do with some mild styling.

<img width="550" alt="Screenshot 2024-03-27 at 17 38 13" src="https://github.com/primefaces/primefaces/assets/7500178/48ccc974-38f3-4de8-aa58-8480f07490c2">

<img width="457" alt="Screenshot 2024-03-27 at 17 41 46" src="https://github.com/primefaces/primefaces/assets/7500178/462711d9-ffed-4a1d-b180-67177a5bc17f">

**Comment by melloware** [comment]
Nice. When I looked years ago the styling of the native select one was limited but the web has come a long way since the last time I looked.

**Comment by jepsar** [comment]
I did a little bit of styling in our project, and the select now looks like:

<img width="418" alt="Screenshot 2024-04-08 at 17 13 35" src="https://github.com/primefaces/primefaces/assets/7500178/e19223bd-5e47-4beb-8f5b-d89bdcab34f9">

**Comment by melloware** [comment]
Definitely an improvement!

**Comment by melloware** [comment]
i have this in the theme and its looking real good.

```css
    select, input {
      color: $inputTextColor;
      background: $inputBg;
      padding: $inputPadding;
      border: $inputBorder;
      outline: 0 none;
      font-size: $inputTextFontSize;
      border-radius: $borderRadius;
      transition: $transition;
      -webkit-appearance: none;
      appearance: none;
    
      &:focus {
        @include focused-input();
      }

      &:hover {
        border-color: $inputHoverBorderColor;
      }
    }
 ```

![image](https://github.com/primefaces/primefaces/assets/4399574/8ddd209f-9316-4c10-8e6c-3299cc9c5307)

However now it throws the paginator centering off which I need to figure out.

The new input styling pushing the icons so everything is not centered.

![image](https://github.com/primefaces/primefaces/assets/4399574/f9d79ebb-66a2-468a-9f85-757379e3d853)
