### ISSUE TITLE
DataTable: Allow using custom icons for p:rowToggler

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#11952]
### Description

We'd like to customize the icons being rendered by `p:rowToggler`, as far as I'm concerned after reading the documentation and looking at `RowToggler`/`RowTogglerRenderer` this isn't possible right now in an intuitive way as icons [are hardcoded](https://github.com/primefaces/primefaces/blob/14.0.0/primefaces/src/main/java/org/primefaces/component/rowtoggler/RowToggler.java#L36-L37)

### Describe the solution you would like

Attributes to define icons being used for expanded/collapsed states like this:
`<p:rowToggler expandIcon="foo" collapseIcon="bar"/> `

**Comment by melloware** [comment]
@jungm you can change it with CSS.

```css
body .ui-datatable .ui-datatable-data>tr .ui-row-toggler.ui-icon-circle-triangle-e {
	font-family: "primeicons" !important;
	font-style: normal;
	font-weight: normal;
	display: inline-block;
	background: none
}

body .ui-datatable .ui-datatable-data>tr .ui-row-toggler.ui-icon-circle-triangle-e:before {
	content: "\e901"
}

body .ui-datatable .ui-datatable-data>tr .ui-row-toggler.ui-icon-circle-triangle-s {
	font-family: "primeicons" !important;
	font-style: normal;
	font-weight: normal;
	display: inline-block;
	background: none
}

body .ui-datatable .ui-datatable-data>tr .ui-row-toggler.ui-icon-circle-triangle-s:before {
	content: "\e902"
}
```

The default icons from PrimeIcons are `\e901` and `\e902` but change to FontAwesome or other PrimeIcons if you want.
