### ISSUE TITLE
DataTable: Style for responsive view when `reflow=true`

### ISSUE THREAD

**Issue by cguerrero1205** [primefaces/primefaces#12571]
### Description

Based on discussion: https://github.com/orgs/primefaces/discussions/2652

When activating reflow on a <p:datatable>, where its columns have a predefined width and then, when viewing the page on a mobile device, the width of the columns did not allow it to be seen correctly, like this:

```xml
<p:dataTable id="tblCicloAR"
             widgetVar="tblCicloAR"
             value="#{cicloARBean.listaCiclo}"
             var="datos"
             paginator="true"
             paginatorPosition="bottom"
             emptyMessage="No se encontraron datos"
             rows="15"
             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
             currentPageReportTemplate="{startRecord}-{endRecord} de {totalRecords} registros"
             rowsPerPageTemplate="15,20,25,30"
             size="small"
             reflow="true">
    <f:facet name="header">                         
        <p:commandButton id="btnNuevo"
                         value="Nuevo"
                         action="#{cicloARBean.nuevoCiclo()}"
                         rendered="#{cicloARBean.permisoCrear}"
                         update="f:dlgCiclo f:mensajes"
                         icon="pi pi-external-link">
        </p:commandButton>
    </f:facet>
    <p:column id="idCiclo"
              headerText="Id"
              filterBy="#{datos.id}"
              filterMatchMode="contains"
              filterStyle="width: 80%; height: 15px"
              style="text-align: center; width: 5%">
        <h:outputText value="#{datos.id}"/>
    </p:column>
    <p:column id="idFechaCiclo"
              headerText="Fecha hora registro"
              filterBy="#{datos.fechaHoraRegistro}"
              filterMatchMode="contains"
              filterStyle="width: 80%; height: 15px"
              style="text-align: center; width: 15%">
        <h:outputText value="#{datos.fechaHoraRegistro}"/>
    </p:column>
    <p:column id="idResponsableNombre"
              headerText="Responsable"
              filterBy="#{datos.nombreResponsable}"
              filterMatchMode="contains"
              filterStyle="width: 80%; height: 15px"
              style="text-align: center; width: 60%">
        <h:outputText value="#{datos.nombreResponsable}"/>
    </p:column>

  ...

</p:dataTable>
```
![image](https://github.com/user-attachments/assets/72887a6a-d243-4546-9c64-78a0dc15e453)

### Describe the solution you would like

This could be solved by adding the following MonkeyPatch to inject the styles to the table:

```js
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.initReflow = function() {
        var headerColumns = this.thead.find('> tr > th');

        for (var i = 0; i < headerColumns.length; i++) {
            var headerColumn = headerColumns.eq(i),
                reflowHeaderText = headerColumn.find('.ui-reflow-headertext:first').text(),
                colTitleEl = headerColumn.children('.ui-column-title'),
                title = (reflowHeaderText && reflowHeaderText.length) ? reflowHeaderText : colTitleEl.text();

            var column = this.tbody.find('> tr:not(.ui-datatable-empty-message,.ui-datatable-summaryrow) > td:nth-child(' + (i + 1) + ')')
            column.find(".ui-column-title").remove(); 
            column.prepend('<span class="ui-column-title" style="width: 100px; font-weight: bold; text-align: left">' + PrimeFaces.escapeHTML(title) + '</span>');

            // Apply styles dynamically
            column.css({
                'width': 'auto'
            });
        }
    };
};
```

Getting this result in the <p:datatable>:

![image](https://github.com/user-attachments/assets/f29d4f5f-ed24-4c16-a8d8-ef5fa4cfc313)

### Additional context

For more information, please refer to this discussion, [clic here](https://github.com/orgs/primefaces/discussions/2652)

**Comment by melloware** [comment]
@cguerrero1205 this can be done with no JS code. Try this CSS override.

```css
    .ui-datatable-reflow .ui-datatable-data td[role="gridcell"]:not(.ui-helper-hidden) { 
        -moz-box-sizing: border-box;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        clear: left;
        float: left;
        border: 0px none;
        display: block;
        text-align: left !important;
        width: 100% !important;
    }
  
    .ui-datatable-reflow .ui-datatable-data td[role="gridcell"] .ui-column-title { 
        display: inline-block;
        font-weight: bold;
        margin: -.4em 1em -.4em -.4em;
        min-width: 30%; 
        padding: .4em;
    }
```

**Comment by cguerrero1205** [comment]
> @cguerrero1205 this can be done with no JS code. Try this CSS override.
> 
> ```css
>     .ui-datatable-reflow .ui-datatable-data td[role="gridcell"]:not(.ui-helper-hidden) { 
>         -moz-box-sizing: border-box;
>         -webkit-box-sizing: border-box;
>         box-sizing: border-box;
>         clear: left;
>         float: left;
>         border: 0px none;
>         display: block;
>         text-align: left !important;
>         width: 100% !important;
>     }
>   
>     .ui-datatable-reflow .ui-datatable-data td[role="gridcell"] .ui-column-title { 
>         display: inline-block;
>         font-weight: bold;
>         margin: -.4em 1em -.4em -.4em;
>         min-width: 30%; 
>         padding: .4em;
>     }
> ```

I applied the changes with using CSS, the responsive view looks fine, but the non-responsive one was damaged:

![image](https://github.com/user-attachments/assets/d85db926-937b-4d50-9aba-7347fa0c7f3a)

**Comment by melloware** [comment]
Sorry it needs to be wrapped in the media query or it will always apply.

```css
@media ( max-width: 640px ) {
    .ui-datatable-reflow thead th,
    .ui-datatable-reflow tfoot td {
        display: none;
    }

    .ui-datatable-reflow .ui-datatable-data td[role="gridcell"]:not(.ui-helper-hidden) { 
        -moz-box-sizing: border-box;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        clear: left;
        float: left;
        border: 0px none;
        display: block;
        text-align: left !important;
        width: 100% !important;
    }
    
    .ui-datatable-reflow .ui-datatable-data.ui-widget-content {
        border: 0px none;
    }
    
    .ui-datatable-reflow .ui-datatable-data tr.ui-widget-content {
        border-left: 0px none;
        border-right: 0px none;
    }

    .ui-datatable-reflow .ui-datatable-data td[role="gridcell"] .ui-column-title { 
        display: inline-block;
        font-weight: bold;
        margin: -.4em 1em -.4em -.4em;
        min-width: 30%; 
        padding: .4em;
    }
    
    .ui-datatable-reflow .ui-reflow-label,
    .ui-datatable-reflow .ui-reflow-dropdown {
        display: inline-block;
    }
    
    .ui-datatable-reflow .ui-reflow-dropdown {
        margin-left: 5px;
        border-top-left-radius: 3px;
        border-bottom-left-radius: 3px;
    }
    
    .ui-datatable-reflow tr.ui-datatable-empty-message > td {
        display: block;
        border: 0 none;
    }
}
```
