### ISSUE TITLE
SelectBooleanCheckbox, ToggleSwitch: NVDA (Screen reader) reads "empty" when focusing

### ISSUE THREAD

**Issue by gipoezcan** [primefaces/primefaces#12577]
### Describe the bug

The NVDA screen reader doesn't recognize the labels for the checkbox and the toggle switch

### Reproducer

1. Activate NVDA
2. go to [the checkbox demo page](http://www.primefaces.org/showcase/ui/input/booleanCheckbox.xhtml) or the [toggle switch demo page](http://www.primefaces.org/showcase/ui/input/toggleSwitch.xhtml?jfwid=a29d8)
3. when you focus on the checkbox or the toggle switch, NVDA just announces "empty" ("leer" in German).

### Expected behavior

The labels of both will be announced

### PrimeFaces edition

Community

### PrimeFaces version

14

### JSF implementation

Mojarra

### JSF version

any

### Java version

any

### Browser(s)

Firefox and Chrome (any version) under Windows 10 and NVDA 2024_3

### Our Workaround

    html .ui-helper-hidden-accessible {
      border: unset;
      clip: unset;
      height: unset;
      margin: unset;
      overflow: unset;
      padding: unset;
      width: unset;
      pointer-events: none;
      opacity: 0;
    }
    
    .ui-helper-hidden-accessible input {
      transform: unset !important;
    }

### Related

https://github.com/primefaces/primefaces/issues/6561

**Comment by melloware** [comment]
nice @gipoezcan its actually related to these two: https://github.com/primefaces/primefaces/pull/11639

We have been blaming NVDA:  https://github.com/nvaccess/nvda/issues/16300

**Comment by melloware** [comment]
so what is interesting about you doing this:

```css
border: unset;
  clip: unset;
  height: unset;
  margin: unset;
  overflow: unset;
  padding: unset;
  width: unset;
```

That is not what any other CSS library from Bootstrap, to Jquery, to Tailwind do.  They all do this.

```css
/* https://stackoverflow.com/a/62109988/502366 */
.ui-helper-hidden-accessible {
    border: 0 !important;
    padding: 0 !important;
    margin: -1px !important;
    position: absolute !important;
    height: 1px !important;
    width: 1px !important;
    overflow: hidden !important;
    clip: rect(1px, 1px, 1px, 1px) !important; /* Legacy Browsers */
    clip-path: inset(50%) !important; /* Modern Browsers */
    white-space: nowrap !important;
}
```

**Comment by melloware** [comment]
so it sounds like NVDA just wants this.

```css
.ui-helper-hidden-accessible {
   pointer-events: none;
  opacity: 0;
}
```
