### ISSUE TITLE
Advanced FileUpload: highlight when drag/drop files

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12942]
When you drag over the advanced fileupload, there is no highlighting 
http://www.primefaces.org/showcase/ui/file/upload/dnd.xhtml?jfwid=f6694

only in our styled custom dropZone in the showcase

**Comment by tandraschko** [comment]
![grafik](https://github.com/user-attachments/assets/690bc726-2f05-4671-8412-e5d6ff44f329)

**Comment by tandraschko** [comment]
thats how i implemented it for now

**Comment by jepsar** [comment]
That looks disabled to me. Can't we do what PrimeVue is doing?

https://primevue.org/fileupload/

```css
.p-fileupload-highlight {
    border: 1px dashed var(--p-fileupload-content-highlight-border-color);
}

:root {
    --p-fileupload-content-highlight-border-color: var(--p-primary-color);
}
```
