### ISSUE TITLE
SelectCheckboxMenu: Add `showSelectAll` attribute

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#13232]
### Description

Client is requesting certain SelectCheckboxMenus to not allow "select all" option. This is doable via CSS with:
```css
body .no-selectall .ui-selectcheckboxmenu-header .ui-chkbox {
    display: none;
}
```
and
```xml
<p:selectCheckboxMenu panelStyleClass="no-selectall" ... />
```

### Describe the solution you would like

I think this should be controlled via an attribute on the component itself, similar to PrimeReact MultiSelect equivalent
https://primereact.org/multiselect/#api.MultiSelect.props.showSelectAll
