### ISSUE TITLE
DataTable: responsive subtable not working

### ISSUE THREAD

**Issue by RueKow** [primefaces/primefaces#1910]
## 1) Environment
- PrimeFaces version: 6.0 (community edition)
- Does it work on the newest PrimeFaces version? I don't know (I'm not ELITE or PRO user)
- Application server + version: Tomcat 8
- Affected browsers: every

## 2) Expected behavior
subtable should accept priority mode
...

## 3) Actual behavior
priority mode will be ignored in subtable
..

## 4) Steps to reproduce
Please add priority tag to datatable/subtable showcase
.. 

## 5) Sample XHTML
see forum http://forum.primefaces.org/viewtopic.php?f=3&t=48151
..

## 6) Sample bean
see forum http://forum.primefaces.org/viewtopic.php?f=3&t=48151
..

**Comment by RueKow** [comment]
I checked it with PF 6.1 Snapshot. The same result.

**Comment by RueKow** [comment]
Sorry for closing. I only want to leave a comment.

**Comment by Qleoz12** [comment]
Hi, I have faced the same situation where I decided to modify the default style of the Primefaces CSS classes in order to leave the subtable as a flex container, and in conjunction with the Grid CSS classes of Primefaces I can achieve my subtable properly, for my case it was inside a tabview.

my parent table must have this properties 
- *reflow="true" 
- *tableStyle="table-layout:auto"

custom CSS
```css
/*make responsive a subtable*/
/* apply to  tr   */
.ui-tabs-panels .ui-tabs-panel.ui-widget-content.ui-corner-bottom.ui-helper-hidden .Container table tbody tr:NTH-CHILD(2) 
{
	display: flex;
	align-items: stretch;
	flex-wrap: wrap;
}
```

file.xhtml 

```xml
<p:tab title="R">
<div class="Container">*

<p:dataTable
value="#{bean.List}"
var="var1"
reflow="true" tableStyle="table-layout:auto"
>
<!-- 									se deja columnGroup para que no salga scrollbar en el bottom de la subtable -->
<p:columnGroup type="header"></p:columnGroup>
		<p:subTable									
		value="#{bean.List}"
		var="var2" id="subtableResponsive" 
		>

				<f:facet name="header">
				<h:outputText
					value="No ( #{var1.id} )" />
				<h:outputText value=" Por " />
				<h:outputText
					value="#{var1.valorTotalRecaudo}">
					<f:convertNumber groupingUsed="true" currencySymbol="$"
						type="currency" />
				</h:outputText>
				</f:facet>

				<p:column   styleClass="ui-g-12 ui-md-1 ui-lg-1"  >
					<h:outputText value="Numero Abono" styleClass="DispBlock"/>
					<h:outputText value="#{var.id}" />
				</p:column>
				<p:column styleClass="ui-g-12 ui-md-1">
					<h:outputText value="No Orden" styleClass="DispBlock"/>
					<h:outputText value="#{var.idOrdenDeCompra}" />
				</p:column>
				<p:column  styleClass="ui-g-12 ui-md-2 ">
					<h:outputText value="Proveedor" styleClass="DispBlock"/>
					<h:outputText
						value="#{var.ordenDeCompra.entidadOrigen.nombre}" />
				</p:column>
				<p:column  styleClass="ui-g-12 ui-md-2 ">
					<h:outputText value="Cliente" styleClass="DispBlock"/>
					<h:outputText
						value="#{var.ordenDeCompra.entidadDestino.nombre}" />
				</p:column>
				<p:column  styleClass="ui-g-12 ui-md-2">
				<h:outputText value="Valor del Abono" styleClass="DispBlock"/>
					<div class="TexAlRight">
						<h:outputText value="#{var.valorAbono}">
							<f:convertNumber groupingUsed="true" currencySymbol="$"
								type="currency" />
						</h:outputText>
					</div>
				</p:column>
				<p:column styleClass="ui-g-12 ui-md-2">
					<h:outputText value="Total del Credito" styleClass="DispBlock"/>
					<div class="TexAlRight">
						<h:outputText
							value="#{var.valorAbonado}">
							<f:convertNumber groupingUsed="true" currencySymbol="$"
								type="currency" />
						</h:outputText>
					</div>
				</p:column>
				<p:column styleClass="ui-g-12 ui-md-2">
					<h:outputText value="Fecha Del Abono" styleClass="DispBlock"/>
					<div class="TexAlRight">
						<h:outputText value="#{var.fechaCreacion}">
							<f:convertDateTime pattern="yyyy-MM-dd HH:m" />
						</h:outputText>
					</div>
				</p:column>

		</p:subTable>
</p:dataTable>

</div>


</p:tab>
```

![captura](https://user-images.githubusercontent.com/15818177/47580639-02d73900-d915-11e8-84e2-c11b832312a5.PNG)



Responsive
![capturaresponsive](https://user-images.githubusercontent.com/15818177/47580647-05d22980-d915-11e8-86fb-b17a6f474acc.PNG)




after use this is better way  
```css
/*make responsive a subtable*/
/* how use this, add subtableResponsive to parent table */
/* apply to  tr   */
.subtableResponsive tbody  tr:not(:first-child)
{
	display: flex;
	align-items: stretch;
	flex-wrap: wrap;
}
```
