### ISSUE TITLE
CSS transition on td wraped in p:layout doen't work as espected: borders aren't displayed

### ISSUE THREAD

**Issue by robertfdx** [primefaces/primefaces#2887]
## 1) Environment
- PrimeFaces version: 6.1 Community Edition
- Affected browsers: Chrome v60 to v62
Works on Chrome v59

## 5) Sample XHTML
```xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<body>

	<p:layout>
		<p:layoutUnit position="north">
			<h:outputText value="north" />
		</p:layoutUnit>

		<p:layoutUnit position="center">
			<p:dataTable var="car" value="#{mb.cars}">
				<p:column headerText="Id">
					<h:outputText value="#{car.id}" />
				</p:column>

				<p:column headerText="Year">
					<h:outputText value="#{car.year}" />
				</p:column>

				<p:column headerText="Brand">
					<h:outputText value="#{car.brand}" />
				</p:column>

				<p:column headerText="Color">
					<h:outputText value="#{car.color}" />
				</p:column>
			</p:dataTable>
		</p:layoutUnit>

	</p:layout>

	<h:outputStylesheet name="styles.css" />
</body>

</html>
```
```css
.ui-datatable table tbody tr td {
	color: #546e7a;
	border: solid 1px #000040;
	font-size: 14px;
	font-family: 'robotoregular';
	transition: all 0.2s ease;
	-webkit-transition: all 0.2s ease;
}
```
## 6) Sample bean: I used the example from the showcase for datatable: https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml
