### ISSUE TITLE
FileUpload: weird CSS Behaviour (200px fontsize)

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2929]
Hi, why does the ui-fileupload input element have a 200px font-size? 

This is causing some strange additional space under some circumstances resulting in scrollbars where they should not appear

![image](https://user-images.githubusercontent.com/13161711/32717873-89ecd6fa-c85b-11e7-9905-21a111c4230b.png)

workaround used:

```css
.ui-fileupload-buttonbar .ui-fileupload-choose input {
	font-size: inherit;
}
```
If there is no known reason to use this, it would be good to change this in the primefaces code
