### ISSUE TITLE
Upgrade to Font Awesome 5.0.2

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#3056]
Incorporate  Font Awesome 5.0.1 (fontawesome-free-5.0.1)

https://fontawesome.com/?utm_source=font_awesome_homepage&utm_medium=display&utm_campaign=fa5_released&utm_content=banner

**Comment by melloware** [comment]
wow 896 icons.  This will most likely be done in 6.3 as PF is trying to button up the 6.2 release now.

**Comment by ravihariharan** [comment]
I got some icons to work. but due to change in 5 some icons will have to changed in code. 

![image](https://user-images.githubusercontent.com/15189434/33787186-1eea679e-dc3a-11e7-857b-be3825b4afee.png)




![image](https://user-images.githubusercontent.com/15189434/33787304-a4011f04-dc3a-11e7-90ef-a6a8d252a506.png)


I can do a PR since this is not a Primefaces issue and will have to done to support "Font Awesome 5" in future.

**Comment by ravihariharan** [comment]
https://github.com/ravihariharan/showcase/blob/master/src/main/webapp/ui/misc/fa.xhtml

**Comment by ravihariharan** [comment]
![image](https://user-images.githubusercontent.com/15189434/33801648-8dd6e51a-dd2f-11e7-8877-8a54847ffd50.png)

Not sure of the impact of removing margin-top:-0.25em from .ui-icon  and hence leaving it as is for now.

**Comment by kukel** [comment]
PF should not include their own version of fontawesome anymore but 'reference' the webjars version.... 
https://stackoverflow.com/questions/18891768/how-to-use-font-awesome-from-webjars-org-with-jsf#28652968

**Comment by mertsincan** [comment]
Thanks a lot for the PR;) 

> Not sure of the impact of removing margin-top:-0.25em from .ui-icon and hence leaving it as is for now.

This issue is fixed.

**Comment by mertsincan** [comment]
Reverted these changes for now.

**Comment by tandraschko** [comment]
Why?

**Comment by tandraschko** [comment]
@mertsincan Also the showcase is completely aligned to 5.x

**Comment by melloware** [comment]
Agree with @tandraschko  the showcase is totally updated and this brings in over 500 new icons.  This is a huge addition to PF 6.2.

**Comment by jxmai** [comment]
Not sure if it is related: Maybe some premium themes will be broken by font-awesome 5 ? At least a lot of built in icons in Atlantis theme disappeared  last time I checked.


**Less file**:

```less
.ui-splitbutton .ui-splitbutton-menubutton .ui-icon{background-image:url("#{resource['primefaces-adamantium:images/menu-dots.svg']}") !important; background-size: 100%; background-position: center;}
```
**The generated css content** is human unreadable using fontawesome 5

```css
body .ui-splitbutton.ui-buttonset .ui-button .ui-icon-triangle-1-s:before {
      content: ""; }
```
