### ISSUE TITLE
<p:dialog> is not centered after changing browser screen size

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3226]
Check here:

https://www.primefaces.org/showcase/ui/overlay/dialog/basic.xhtml

Open "Basic" Dialog, then resize the browser, if you got a big screen it, the dialog might even be invisible. 

I will make a PR soon, but i still need to figure out the best way to do this without breaking other settings like draggable.

**Comment by cnsgithub** [comment]
It seems that setting responsive to true will properly bind the resizeListener. So i guess this was intended? In any case, i don't see any disadvantage in using this attribute, so maybe make it default true? 

dialog.js
```javascript
    if(this.cfg.responsive) {
            this.bindResizeListener();
        }
```

This was the CSS workaround i used before, so maybe it could be used instead of doing complex JS-recalculation when the initial position is centered

```css
.ui-dialog {
	border: none !important;
	position: fixed;
	top: 50% !important;
	left: 50% !important;
	transform: translate(-50%, -50%);
}
```
