### ISSUE TITLE
Horizontal Tree: TreeNode styleClass not respecting Node EL variable

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#3444]
**Version:** PF 6.1.13 and PF 6.2

**Screenshot:**
![image](https://user-images.githubusercontent.com/4399574/37102245-6aca310c-21f5-11e8-8e6b-e06f3baf9bd9.png)

We are trying to use StyleClass of TreeNode to color the treenode border based on the content of the node.  It appears using an EL expression in the styleClass() leads to the Node value being the previous value every time or off by 1 starting with the root.

We have attached an example Test project that shows the issue.  The border colors should be RED, GREEN, BLUE but you can see they are all shifted by one color.

```xml
<p:tree  value="#{testView.treeNode}" var="node" orientation="horizontal">
	<p:treeNode styleClass="custom-node border-#{node.color}">
		<h:outputText value="#{node.color}" title="#{node.color}" />
	</p:treeNode>
</p:tree>
```

```css
.custom-node .ui-treenode-content {
	background-color: white;
	color:black;
	background-image:none;
	border:1.5px solid black;
}

.border-RED .ui-treenode-content {
	border:1.5px solid red !important;
}

.border-GREEN .ui-treenode-content {
	border:1.5px solid green !important;
}

.border-BLUE .ui-treenode-content {
	border:1.5px solid navy !important;
}
```

Runnable Project to demonstrate the issue: [primefaces-test-treenode.zip](https://github.com/primefaces/primefaces/files/1789766/primefaces-test-treenode.zip)
