### ISSUE TITLE
SlideMenu: is only displayed once if the p:commandLink trigger has an AJAX update itself

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3921]
## 1) Environment
- PrimeFaces version: 6.2, 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No. 6.3-SNAPSHOT
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: Payara 4.1.2.181
- Affected browsers: Chrome

## 2) Expected behavior

The user should be able to open the `p:slideMenu` `slideMenu` every time he_she clicks on the `trigger` component `menuTrigger`, no matter whether the `trigger` has an `update` or `listener` attribute.

I'm filing this as bug after a recommendation by @melloware  at https://stackoverflow.com/questions/51633006/how-to-be-able-to-display-a-pslidemenu-more-than-once-if-the-pcommandlink-trig?noredirect=1#comment90233840_51633006.

## 3) Actual behavior

The `p:slideMenu` is only displayed the first time, once it has been hidden, clicking the trigger component has no effect.

## 4) Steps to reproduce

`.gitlab-ci.yml` of SSCCE provided at https://gitlab.com/krichter/primefaces-open-slide-menu-with-selenium:

```
main:
    image: maven:slim
    script:
        - apt-get update && apt-get install --yes chromium git
        - git clone https://github.com/primefaces/maven-jsf-plugin.git && cd maven-jsf-plugin && mvn --batch-mode install && cd ..
        - git clone https://github.com/primefaces/primefaces.git && cd primefaces && mvn --batch-mode install && cd ..
        - mvn --batch-mode install -Dbrowser=chromeheadless
```

Removing the `update` attribute from `p:ajax` avoids the issue, but removes the effect of the `update`.

## 5) Sample XHTML

```
<h:form id="mainForm">
    <p:commandLink id="menuTrigger"
            value="Open slide menu"
            style="background: #{backingBean0.background};">
        <p:ajax listener="#{backingBean0.listener0()}"
                update="menuTrigger"/>
    </p:commandLink>
    <p:slideMenu id="slideMenu"
            trigger="menuTrigger"
            overlay="true"
            triggerEvent="click"
            my="left top"
            at="left bottom"
            style="width:180px;">
        <p:menuitem id="menuItem1"
                value="Menu item 1"/>
    </p:slideMenu>
    <p:outputLabel id="menuHideLabel"
            value="Hide slide menu"/>
</h:form>
```

## 6) Sample bean

```
@Named
@ViewScoped
public class BackingBean0 implements Serializable {
    private static final long serialVersionUID = 1L;
    private String background = "";

    public void listener0() {
        System.out.println("listener0");
        background = "green";
    }

    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }
}
```
