### ISSUE TITLE
Remove CSS scale from Advanced FileUpload

### ISSUE THREAD

**Issue by stephanrauh** [primefaces/primefaces#460]
The fileupload.css contains a very strange line that causes errors - for instance, see [this bug](https://github.com/TheCoder4eu/BootsFaces-OSP/issues/110) which has been reported on the BootsFaces page. As it turns out, it's a PrimeFaces bug, which in turn is a bug you've inherited from the FileUpload jQuery plugin.

The offending line is:

``` CSS
.ui-fileupload-buttonbar .ui-fileupload-choose input {
   ...
   transform: translate(-300px, 0) scale(4);
   ...
}
```

As a quick fix, it suffices to remove the line.

However, when I looked at the jQuery plugin page, I noted that the author removed this line a long time ago. He also published a lot of releases in the meantime. Would you mind to update to the current version?
