### ISSUE TITLE
Controlling Font Performance with font-display

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#4619]
Based on findings with Google Lighthouse I think we need to add the CSS property "font-display" to the CSS.

You can read what Google says about this property here so I am not quite sure the correct setting should be "swap" or "fallback" but I figured you guys would do some internal testing.

```css
@font-face {
    font-family: 'PrimeIcons';
    font-display: swap;
    src: url('fonts/primeicons.eot');
    src: url('fonts/primeicons.eot?#iefix') format('embedded-opentype'), url('fonts/primeicons.ttf') format('truetype'), url('fonts/primeicons.woff') format('woff'), url('fonts/primeicons.svg?#primeicons') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

It looks line FontAwesome chose "font-display: auto;".

https://github.com/FortAwesome/Font-Awesome/blob/master/css/all.css#L4262
