### ISSUE TITLE
DataTable: header area width is not same as table body when scrollWidth set

### ISSUE THREAD

**Issue by maruTA-bis5** [primefaces/primefaces#5453]
## 1) Environment
- PrimeFaces version: 8.0.RC1
- Does it work on the newest released PrimeFaces version? Version? Yes. It works on 7.0 (community)
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No. commit 0216064df6045887680a3dcc0296d4ec37ceb211
- Application server + version: WildFly 18.0.1
- Affected browsers: All

## 2) Expected behavior
The header area width is same as table body.

![image](https://user-images.githubusercontent.com/1310661/71051376-7aa49a80-218b-11ea-9423-5cf3119acbc1.png)

## 3) Actual behavior
The header area is 10px wider than table body.

![image](https://user-images.githubusercontent.com/1310661/71051392-85f7c600-218b-11ea-99ef-3a1022dd16bf.png)

## 4) Steps to reproduce
No steps required. Access the page.

## 5) Sample XHTML
```xml
<p:dataTable scrollable="true" scrollWidth="500">
    <f:facet name="header">scrollable &amp; scrollWidth=500</f:facet>
    <p:column headerText="column1" />
    <p:column headerText="column2" />
    <p:column headerText="column3" />
</p:dataTable>
```

## 6) Sample bean
No backing bean required.

Test project is available on: https://github.com/maruTA-bis5/primefaces-test/tree/datatable-header-width

**Comment by melloware** [comment]
Most likely one of these issues introduced it between 7.0 and 8.0.
https://github.com/primefaces/primefaces/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%228.0.RC1%22+scrollable

**Comment by Rapster** [comment]
Since it's a regression, I think it should be in 8.0.RC2 scope

**Comment by melloware** [comment]
Looks like RC2 was just released so I removed the milestone.

**Comment by Rapster** [comment]
Ah I see, I guess a new milestone has to be created then @tandraschko?

**Comment by melloware** [comment]
Its the 10px padding.
```css
.ui-datatable .ui-datatable-header, .ui-datatable .ui-datatable-footer {
    text-align: center;
    padding: 4px 10px;
}
```
Try adding this to your page and see if it fixes your issue.
```css
.ui-datatable .ui-datatable-header, .ui-datatable .ui-datatable-footer {
    text-align: center;
    padding: 4px 0px;
}
```

**Comment by maruTA-bis5** [comment]
> Try adding this to your page and see if it fixes your issue.
> 
> ```css
> .ui-datatable .ui-datatable-header, .ui-datatable .ui-datatable-footer {
>     text-align: center;
>     padding: 4px 0px;
> }
> ```

There is still 2px difference. (source: https://github.com/maruTA-bis5/primefaces-test/commit/111a70ca53ccd86a7efea3bdcbf51d2ce7adec35)
(2px = left + right border width)
![image](https://user-images.githubusercontent.com/1310661/71944187-59712000-3206-11ea-8da5-29334c995f45.png)

**Comment by melloware** [comment]
Thanks for testing. you are right something is still off.

**Comment by mertsincan** [comment]
Please try;
```
.ui-datatable .ui-datatable-header, 
.ui-datatable .ui-datatable-footer {
   -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

Best Regards,

**Comment by melloware** [comment]
I just ran into this with the Altantis 2.0.1 theme and my fix for anyone else looking is...

```css
body .ui-datatable .ui-paginator,
body .ui-datatable .ui-datatable-header, 
body .ui-datatable .ui-datatable-footer {
   -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```
