### ISSUE TITLE
p:steps CSS issues

### ISSUE THREAD

**Issue by ova2** [primefaces/primefaces#548]
`.ui-steps-item` should have `box-sizing: border-box`. Otherwise, the border will be considered while width calculation. If you set

``` css
.ui-steps .ui-steps-item {
    box-sizing: border-box;
}
```

you don't need to set `width: 24%` anymore in this example http://www.primefaces.org/showcase/ui/menu/steps.xhtml You can set `25%` which is the right size for 4 items.

``` css
.ui-steps .ui-steps-item {
    width: 25%;
}
```

Furthermore, please remove `margin-left: 10px;` for `.ui-steps-title`. Otherwise, items are not well aligned. Currently, we have to do this manuelly:

``` css
.ui-steps .ui-steps-title {
    margin-left: 0;
}
```
