### ISSUE TITLE
Sidebar: Modal doesnt block clicks to view

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6245]
It worked correctly in 8.0 
the sidebar closed when clicking in the modal / elements on the "hidden" view

**Comment by tandraschko** [comment]
@melloware you did some fixes here in the sidebar, could you please check it? its easy reproducable in the showcase

**Comment by melloware** [comment]
Yep its when I was fixing #1991 and #5948 I added the same `pointer-events` to all modal masks.  I need to remove them from Sidebar.

Was:
```css
.ui-sidebar-mask {
    position: fixed;
    width: 100%;
    height: 100%;
}
```

I made it:
```css
.ui-sidebar-mask {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

because it all other modal situations users want keyboard and mouse blocked in the modal area so you can
