### ISSUE TITLE
DataTable: use position:sticky for Sticky Header

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6410]
Sticky Header is currently solved with JS.

With position: sticky there´s a native CSS-feature for this. (see https://developer.mozilla.org/en-US/docs/Web/CSS/position)
All browsers except IE11 implement this.
Maybe we should have a look at this. I´ll hope this works more stable than our current solution.

There are currently some open issues regarding this: https://github.com/primefaces/primefaces/issues?q=is%3Aissue+is%3Aopen+sticky

**Comment by christophs78** [comment]
https://css-tricks.com/position-sticky-and-table-headers/

**Comment by melloware** [comment]
Agreed the current Sticky in Datatables has caused a lot of issues.  Maybe we can do an if `Primefaces.isIE()` and use the current sticky but use CSS for all other browsers?

**Comment by mertsincan** [comment]
Please see my comment; https://github.com/primefaces/primefaces/issues/4469#issuecomment-457107038

**Comment by mertsincan** [comment]
Please try the following code on https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml
```
body .ui-datatable-tablewrapper {
    overflow: visible;
}

body .ui-datatable thead th {
    position: sticky;
    top: 140px;
    box-shadow: 0 1px #c8c8c8;
}
```

**Comment by christophs78** [comment]
We have to put some attention to top-property:

With theme-banner:
![image](https://user-images.githubusercontent.com/10461942/96261143-550d3b00-0fc0-11eb-87c7-ea394de94330.png)

Without theme-banner:
![image](https://user-images.githubusercontent.com/10461942/96261235-753cfa00-0fc0-11eb-9ab8-eb56fcc491d0.png)

The combination with filter does not cause extra issues:
![image](https://user-images.githubusercontent.com/10461942/96261400-b2a18780-0fc0-11eb-8e6e-f517b29900a3.png)

**Comment by christophs78** [comment]
Do we need to set top-property dynamic via JS? (And update it on window-resize-event, after ajax-updates, ...)

**Comment by stolp** [comment]
I think this is related to what I raised in #5387

**Comment by melloware** [comment]
@stolp is correct see my comment: https://github.com/primefaces/primefaces/issues/5387#issuecomment-608728849  So yes i think Top needs to be done with JS not calculated once at the start of the page.

**Comment by christophs78** [comment]
From it´s basic idea 
```css
body .ui-datatable thead th {
    position: sticky;
    top: 0px;
}
```
would do it´s job without extra JS.

The issue why this does not work seems to be because of:
```css
.layout-wrapper .layout-news.layout-news-active + .layout-topbar + .layout-sidebar + .layout-content {
    padding-top: 140px;
}
```

Mert tries to compensate this with 
```css
body .ui-datatable thead th {
    position: sticky;
    top: 140px;
}
```

I´ll hope we may find a other way than fiddling arround with JS all the time to adjust top-property dynamically.
