### ISSUE TITLE
BreadCrumb: should be able to be responsive

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6480]
If all the items don't fit on one line, the items at the beginning of the trail should be consolidated in a navigation item which will allow you to show the hidden items.

See #6478

**Comment by mertsincan** [comment]
Hi @jepsar,

Many thanks for your great effort! BreadCrumb can be responsive by default and a scrollbar may appear in mobile mode like https://primefaces.org/primereact/showcase/#/breadcrumb

Best Regards,

**Comment by jepsar** [comment]
If you don't like a scrollbar, this could be an alternative:
```scss
  body .ui-breadcrumb .ui-breadcrumb-items li {
    .ui-menuitem-link {
      max-width: 50px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    & .ui-menuitem-link:focus,
    &:hover .ui-menuitem-link,
    &:first-child .ui-menuitem-link,
    &:nth-last-child(2) .ui-menuitem-link,
    &:nth-last-child(1) .ui-menuitem-link {
      max-width: none;
    }
  }
```
