### ISSUE TITLE
DataTable/TreeTable: Multisort priority indicator

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6728]
**Description**
We have been using this in our production apps for years but the idea is for multi-sort a way of identifying the order of the columns sorted.

**Describe the solution you would like**
When a table has multisort and more than 1 column is sorted show a visual indicator of the sort order.  If only 1 column is sorted there is no need for such priority indicator.

**Additional context**
_Example with 1 column sorted:_
![image](https://user-images.githubusercontent.com/4399574/103239409-6c9b6500-491b-11eb-9599-9e0ad7ff4779.png)

_Now with 3 columns sorted:_
![image](https://user-images.githubusercontent.com/4399574/103239488-9f455d80-491b-11eb-8a3e-1e6fa4d0bf4d.png)

**Comment by tandraschko** [comment]
Maybe the PrimeTek designer has a good Idea? @cagataycivici @mertsincan ?

**Comment by melloware** [comment]
I submitted my PR for review.  The styling would have to be changed in the themes but here is all they would have to override:
```css
.ui-datatable .ui-sort-priority {
    font-size: .8em;
    font-weight: bold;
    color: $sassVariable;
    background: $sassVariable;
    padding: 2px 6px;
    border-radius: 8px;
    margin: -3px 0px -3px 2px; // probbaly sass variable too
    position: relative;
}
```

**Comment by mertsincan** [comment]
Hi all,

Thanks a lot for your efforts! Could you please check 'Multiple Columns' example in https://primefaces.org/primereact/showcase/#/datatable/sort?

@melloware can add CSS styles related to alignment to the core. The rest of the styles can come from the Theme.

**Comment by melloware** [comment]
Perfect let me look at those styles and change mine to use that so you can simply override with the Themes.  I will update my PR.

**Comment by melloware** [comment]
OK looked at Primereact and updated my PR with CSS to match it only doing alignment.
```css
/* Multiple sort number badges */
.ui-datatable .ui-sort-priority {
    display: -ms-inline-flexbox;
    display: inline-flex;
    -ms-flex-align: center;
    align-items: center;
    -ms-flex-pack: center;
    justify-content: center;
    vertical-align: middle;
}

/* Multiple sort number badges */
.ui-treetable .ui-sort-priority {
    display: -ms-inline-flexbox;
    display: inline-flex;
    -ms-flex-align: center;
    align-items: center;
    -ms-flex-pack: center;
    justify-content: center;
    vertical-align: middle;
}
```
