### ISSUE TITLE
Checkbox: Regression, custom styling of checkbox active state no longer working

### ISSUE THREAD

**Issue by Helveticus** [primefaces/primefaces#6834]
**Describe the defect**
The custom styling for a checkbox actiove state is no longer working.  I am no CSS expert, but I had to add an additional attribute selector to bring it back into working order.   

**Reproducer**
n/a

**Environment:**
 - PF Version: 10.0 Snapshot
 - JSF + version: _e.g. Mojarra 2.3.9
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**

**Expected behavior**

// PF 8.0
```css
.ui-chkbox-box.ui-state-active {
    border-color: #007ad9;
    background-color: #007ad9;
    color: #000;
}
```

// PF 10.0
```css
.ui-chkbox-box.ui-state-active, .ui-chkbox-box[aria-checked='true'] {
    border-color: #007ad9;
    background-color: #007ad9;
    color: #000;
}
```
