### ISSUE TITLE
Themes: Reduce size

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6899]
**Description**
I use the Theme Designer for our clients and we noticed we can reduce the theme.css generated from 250KB down to 150KB with a simple change to how the icons are declared.  Assigning this to @mertsincan for review since he is the CSS expert and Theme master.

**Describe the solution you would like**
Change the icon declaration to DRY principal (Dont repeat yourself).

**Current mixins.scss**
```css
// Icon Override Mixin
@mixin icon_override($icon) {
    font-family: 'primeicons';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    display: inline-block;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-indent: 0px !important;
    text-align: center;
    background: none;
    display: inline-block;
    font-size: $iconFontSize;

    &:before {
        content: $icon;
    }
}
```

**Proposed Changes**

mixins.scss
```css
@mixin icon_override($icon) {
    font-family: 'primeicons';
    font-weight: normal;
    background: none;
    display: inline-block;
   
    &:before {
        content: $icon;
    }
}
```

common.scss
```css
    .ui-icon {
        speak: none;
        font-style: normal;
        font-variant: normal;
        text-transform: none;
        line-height: 1;
        display: inline-block;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-indent: 0px !important;
        text-align: center;
        display: inline-block;
        font-size: $iconFontSize;
    }
```

This now reduces the generated CSS by almost 100K and in production we have not noticed any issues with PF doing this.
