### ISSUE TITLE
Password: ToggleMask Icons 

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6975]
**Description**
Need toggle mask icons for password added to theme.

```css
 .ui-password-masked:before {
     content: "\e966";
}
            
.ui-password-unmasked:before {
     content: "\e965";
}
```

Related to: https://github.com/primefaces/primefaces/issues/6919
