### ISSUE TITLE
Slider: cursor grab

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#7063]
**Description**
The cursor style is not 'grab' 

**Describe the solution you would like**
The cursor style should be 'grab' like in PrimeVue p-slider

**Additional context**

inside **theme.css** the class  **"body .ui-slider .ui-slider-handle"**
does not define the cursor style

**Example XHTML**
```xml
<h:form id="frmTest">
         <h5 class="p-mt-0">Basic</h5>
        <h:panelGrid columns="1" >
            <p:inputText id="txt" value="#{sliderView.number1}"/>
            <p:slider for="txt" range="false"/>
        </h:panelGrid>
</h:form>
```

**Example Bean**
```java
@Named
@RequestScoped
public class SliderView {

    private int number1 = 50;

    public int getNumber1() {
        return number1;
    }

    public void setNumber1(int number1) {
        this.number1 = number1;
    }

}
```

**Solution**
```css
body .ui-slider .ui-slider-handle {
    width: 1.143rem;
    height: 1.143rem;
    background: #ffffff;
    border: 2px solid #2196F3;
    transition: background-color 0.2s, color 0.2s, border-color 0.2s, box-shadow 0.2s;
    border-radius: 50%;
    cursor: grab;
}

```
