### ISSUE TITLE
TreeTable: display an extra line in header when scrollable="true"

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#7070]
**Describe the defect**
 Theme/Layout problem when treetable has scrollable="true".
  
**Environment:**
PF Version: 10.0.0-RC2
JSF + version: JSF 2.2.19
Affected browsers: Chrome, Safari 

**To Reproduce**
1. Insert  **scrollable="true"**  in a **<p:treeTable/>** component
2. When filtered, tree table now displays an extra line in header (including sortIcons) with class="ui-treetable-scrollable-theadclone".
```
 <p:treeTable value="#{relatorioBean.root}" var="item"  	
		      scrollable="true"     sortBy="#{item.data}" />  
```

**Possible solution/workaround**
custom.css
```
.ui-treetable-scrollable-theadclone{
	display: none;  
}
```

**Comment by melloware** [comment]
Datatable CSS:
```css
.ui-datatable-scrollable-theadclone {
    height:0px;
}

.ui-datatable-scrollable-theadclone tr {
    height:0px;
}

.ui-datatable-scrollable-theadclone th.ui-state-default {
    height:0px;
    border-bottom-width: 0px;
    border-top-width: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    outline: 0 none;
}

.ui-datatable-scrollable-theadclone th span.ui-column-title {
  display: block;
  height: 0px;
}
```

TreeTable CSS:
```css
.ui-treetable-scrollable .ui-treetable-scrollable-theadclone tr th > * { 
    display: none;
}

.ui-treetable-scrollable-theadclone {
    height:0px;
}

.ui-treetable-scrollable-theadclone tr {
    height:0px;
}

.ui-treetable-scrollable-theadclone th.ui-state-default {
    height:0px;
    border-bottom-width: 0px;
    border-top-width: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    outline: 0 none;
}

.ui-treetable-scrollable-theadclone th span {
  display: block;
  height: 0px;
}
```

SO I think the only difference is this needs to change
```css
.ui-treetable-scrollable-theadclone th span.ui-column-title {
  display: block;
  height: 0px;
}
```

**Comment by melloware** [comment]
Agreed this doesn't look right. Working on a fix...
![image](https://user-images.githubusercontent.com/4399574/110113293-e9661780-7d80-11eb-9711-26ddb4b95078.png)

**Comment by tandraschko** [comment]
and why does it work here? http://primefaces.org/showcase/ui/data/treetable/scroll.xhtml?jfwid=4099b

**Comment by melloware** [comment]
I have a feeling the multisort indicator's are somehow throwing this logic off and making the height 14px when it should be 0px.

**Comment by melloware** [comment]
Ahh I see the sort icon does not have ui-helper-hidden while everything else does.  Let me look why that is.

**Comment by melloware** [comment]
I have the right fix.  The theme's icon CSS was more specific and setting display back to `inline-block`
![image](https://user-images.githubusercontent.com/4399574/110121134-0227fa80-7d8c-11eb-8914-d4541bdd5aa5.png)

The right fix is to make our components.css style more specific...
```css
body .ui-treetable.ui-treetable-scrollable .ui-treetable-scrollable-theadclone tr th > * {
    display: none;
}   
```
