### ISSUE TITLE
DatePicker: time icon problem

### ISSUE THREAD

**Issue by tsobis** [primefaces/primefaces#7114]
The datePicker component has a css problem, when the component includes time, the arrows for changing the time do not appear

PF Version: 10.0.0
 
[showcase examples](
https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml)
check examples
Look at examples
Time (Min-Max)
Time Only (Min-Max)
Time (German)
Time Only
Time

the component has from the css file
https://github.com/primefaces/primefaces/blob/53e480465f9009f5223f75cbdd66af9f2e7b8dde/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.css#L353

the text indent is wrong
```css
text-indent: -99999px;
```

in my case i just added this code on my custom css
```css
.ui-datepicker .ui-icon {text-indent: 0!important;}
```

but i believe it can also be removed from the jquery.ui.css file

**Comment by melloware** [comment]
This style is more specific and prevents the use of `!important`.
```css
.p-datepicker-panel .ui-timepicker .ui-icon {
    text-indent: 0;
}
```
