### ISSUE TITLE
Add "ui-panelgroup" and "ui-panelgroup-addon" class slector. 

### ISSUE THREAD

**Issue by wklaczynski** [primefaces/primefaces#7117]
**Description**
Same as for input "ui-inputgroup", but adding panels to the group. Thanks to this style, you will be able to combine components into groups. 

```css
.ui-panelgroup {   
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}

.ui-panelgroup .ui-panelgroup-addon {
    display: inline-block;
    text-align: center;
    min-width: 1.5em;
    border-width: 1px;
    border-style: solid;
}

.ui-panelgroup .ui-panelgroup-addon {
    padding: 4px;
}

.ui-panelgroup > .ui-corner-all:not(:first-child),
.ui-panelgroup > .ui-corner-left:not(:first-child) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    border-left-width: 0;
}

.ui-panelgroup > .ui-corner-all:not(:last-child),
.ui-panelgroup > .ui-corner-right:not(:last-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
    border-right-width: 0;
}

.ui-panelgroup .ui-panelgroup-addon + .ui-panelgroup-addon {
    border-left: 0 none;
}

.ui-panelgroup .ui-panelgroup-addon:not(:first-child) {

}

.ui-panelgroup .ui-button .ui-button-text {
    padding-bottom: 4px;
    padding-top: 4px;
}
```

**Example XHTML**
```xml
<h:panelGroup layout="block" styleClass="panel-items-layout-left ui-panelgroup">
         <p:panel styleClass="ui-panelgroup-addon portal-panel-vertical-toolbar">
                <p:commandButton
        ......................
          </p:panel>
          <p:tree 
                  value="#{pui_page_menuitems.root}" 
                  var="item"/>
           ...........
           </p:tree>
</h:panelGroup>    
```
![obraz](https://user-images.githubusercontent.com/2326804/111011358-630d8f00-8399-11eb-977f-03919cb9bc50.png)

**Comment by wklaczynski** [comment]
Maybe the same for vertical panels. 

```css

.ui-panelgroup-vertical {   
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    flex-direction: column;
}

.ui-panelgroup-vertical .ui-panelgroup-addon {
    display: inline-block;
    text-align: center;
    min-width: 1.5em;
    border-width: 1px;
    border-style: solid;
}

.ui-panelgroup-vertical .ui-panelgroup-addon {
    padding: 4px;
}

.ui-panelgroup-vertical > .ui-corner-all:not(:first-child),
.ui-panelgroup-vertical > .ui-corner-left:not(:first-child) {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    border-top-width: 0;
}

.ui-panelgroup-vertical > .ui-corner-all:not(:last-child),
.ui-panelgroup-vertical > .ui-corner-right:not(:last-child) {
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
    border-bottom-width: 0;
}

.ui-panelgroup-vertical .ui-panelgroup-addon + .ui-panelgroup-addon {
    border-bottom: 0 none;
}

.ui-panelgroup-vertical .ui-panelgroup-addon:not(:first-child) {

}

.ui-panelgroup-vertical .ui-button .ui-button-text {
    padding-left: 4px;
    padding-right: 4px;
}
```
