### ISSUE TITLE
Dialog: resizeable not working

### ISSUE THREAD

**Issue by Ponferson** [primefaces/primefaces#7154]
**Describe the defect**
resizeable is broken.

**Reproducer**
Just have a look in the showcase. 
www.primefaces.org/showcase/ui/overlay/dialog.xhtml
The basic dialog with resizeable does not work.

**Environment:**
 - PF Version: 10

**Comment by melloware** [comment]
The theme.css is doing this for some unexplained reasoned.
```css
body .ui-dialog .ui-resizable-handle {
    display: none !important;
}
```
If you go into Chrome and uncheck it the resizing works fine!
![image](https://user-images.githubusercontent.com/4399574/111995762-abdaeb80-8aef-11eb-9940-05383de55cca.png)

**Comment by melloware** [comment]
To fix this right now add this CSS to your application to override the theme.css
```css
body .ui-dialog .ui-resizable-handle {
    display: inherit !important;
}
body .ui-dialog .ui-resizable-handle.ui-icon {
    position: absolute;
}
```

**Comment by melloware** [comment]
OK if you use `responsive="true"` and remove this style the dialog is messed up.  I think there is some definite theme work that needs to happen here.

**Comment by Ponferson** [comment]
I think the dialog still needs a background. When I change the style classes in the showcase, the enlarged background is transparent. In addition, the dialog content decreases in size after a vertical reduce.

**Comment by melloware** [comment]
Try giving the dialog a starting height and width like `height="300" width="300"` .

**Comment by melloware** [comment]
There definitely looks like some theme work is needed to fix this.

**Comment by melloware** [comment]
Try and add this style as well:
```css
body .ui-dialog .ui-resizable-handle.ui-icon {
    position: absolute;
}
```

**Comment by tsobis** [comment]
The first thing I see is that the 
.ui-resizable-handle .ui-resizable-se 
gets from jquery the .ui-icon and.ui-icon-gripsmall-diagonal-se 
which are not necessary and take the SE hot spot location to the wrong location. 

After removing it with something like,
```
jQuery(document).ready(function()
         {
            jQuery(".ui-resizable").find("div.ui-resizable-se").removeClass("ui-icon");
            jQuery(".ui-resizable").find("div.ui-resizable-se").removeClass("ui-icon-gripsmall-diagonal-se");

         });
```
some styling is needed
for fixing the problem from the theme.css 
```
body .ui-dialog .ui-resizable-handle {
    display: inherit !important;
}
```

for fixing the location of the se
```
.ui-dialog  .ui-resizable-se {
    cursor: se-resize; 
    width: 9px;
    height: 9px;
    right: -5px;
    bottom: -5px;
}
```
Finally I believe that the container should have something like this
```
body .ui-dialog .ui-dialog-content {
    width: 100% !important; 
    border: 0;
}

```
I do not know if this helps, I have checked it with an empty page and two dialog windows one with resizable="true" and one without it.

However, if you want to keep the ui-icon and the ui-icon-gripsmall-diagonal-se please tell me check for another  solution.

Please try it and see if it fixes your problem and I know that !important is not good but for solving your problem…

**Comment by tsobis** [comment]
The problem with the .ui-icon .ui-icon-gripsmall-diagonal-se 
is that the theme.css has position that overwrites the default position 
```
body .ui-icon {    
    position: static;
}
```
That is why I suggest to remove them with jquery, you could try to change the  position of the ui-icon as well

**Comment by melloware** [comment]
@tsobis This all feels like CSS that needs to be fixed in the Theme and should take care of everything.

**Comment by tsobis** [comment]
Ok, I am a bit confused do you want to remove the 
```
body .ui-dialog .ui-resizable-handle {
    display: none !important;
}
```
because it has the !important?
Can the change be to the file
primefaces\src\main\resources\META-INF\resources\primefaces\dialog\dialog.css

line 6 
`.ui-dialog .ui-dialog-content {position: relative; border: 0; padding: .5em 1em; background: none; overflow: auto;}`

and at the end of the file add
```
body .ui-dialog .ui-resizable-handle {
    display: inherit!important;
}
body .ui-dialog .ui-resizable-handle.ui-icon.ui-icon-gripsmall-diagonal-se {
    position: absolute;
}
body .ui-dialog .ui-dialog-content {
    box-sizing: content-box;
    border: 0;
}
```
I have tested the change with the dialog.css file with a simple dialog and works,
do you want me to test it with something specific, with other components?
Furthermore, the older version had an image at the bottom right, should the image be added?

**Comment by melloware** [comment]
I feel like the draggable handle image is important to show people its resizable.  I noticed it was missing also.  

Let me test out the above.

**Comment by tsobis** [comment]
Sorry i did not change the line 6 at all

**Comment by tsobis** [comment]
It is a bit weird although it seems to work, after multiple resizes the scroll it seems to shrinking each time. I will check it again.

**Comment by tsobis** [comment]
@melloware So, I did not want to add images since I checked and the project does not have many, instead I used a primeicon and rotate it.
Please check this version is way better. If it is ok tell me to PR it. If you want me to test something specific, tell me.


```css
body .ui-dialog .ui-resizable-handle {
    display: inherit!important;
}
body .ui-dialog .ui-resizable-handle.ui-icon.ui-icon-gripsmall-diagonal-se {
    position: absolute;
    transform: rotate(-90deg);
    -webkit-transform: rotate(-90deg);
    -moz-transform: rotate(-90deg);
    -ms-transform: rotate(-90deg);
    -o-transform: rotate(-90deg);
    width: 19px;
    height: 21px;
}
body .ui-dialog .ui-resizable-handle.ui-icon.ui-icon-gripsmall-diagonal-se:before {
    display: block;
    font-family: "primeicons" !important;
    content:"\e93c";
    font-size: 16px;
}
body .ui-dialog .ui-resizable-se {
    right: 0;
    bottom: 0;
    display: block!important;
}

body .ui-dialog.ui-resizable .ui-dialog-content {
    padding: 0 1em 1.2em 1em;
    margin: 0 .4em 1.4em .4em;
    box-sizing: content-box;
    border: 0;
}
```
