### ISSUE TITLE
SelectOneMenu: focused styling (outline) not visible with ui-state-error

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7582]
**Describe the defect**
No outline on focused one menu with error.

**Reproducer**
Just create a form with a required `p:selectOneMenu`, leave blank and submit and update the form.

**Environment:**
 - PF Version: _10.0_
 - Theme: Saga

**Comment by jepsar** [comment]
There is even a specific rule to prevent this: `body .ui-selectonemenu.ui-state-focus:not(.ui-state-error)`, but no such rule for basic `p:inputText` fields.

By the way, `p:inputText` with `ui-state-error` show a blue outline when focussed. Not really clear IMO.

I think this will be much clearer:
```css
body .ui-state-focus.ui-state-error:not(.ui-selectonemenu-trigger) {
    border-color: #f44336;
    outline: 0 none;
    box-shadow: 0 0 0 0.2em #FFCDD2;
}
```

<img width="300" alt="Screenshot 2021-07-14 at 14 36 14" src="https://user-images.githubusercontent.com/7500178/125623043-24edc8ad-f7ee-4a2a-a083-d9bcb96b6b51.png">
