### ISSUE TITLE
Avatar: Fallback logic

### ISSUE THREAD

**Issue by JensPiegsa** [primefaces/primefaces#7661]
**Description**

I'm just trying to get familiar with the new avatar widget in PrimeFaces 10.

From my point of view, the widget could become even more useful if it would implement some kind of fallback logic.

E.g.
* gravatar image -> letters or
* custom image -> gravatar image -> letters or
* custom image -> gravatar image -> icon

I tried to implement the first case using PF 10. However, this required two stacked avatar elements and lots of manual adjustments.

**Describe the solution you would like**

It would be great to have a single avatar widget that includes some sort of fallback logic.

* gravatar can be adjusted via `?d=404` to return a 404 HTTP status code, if there doesn't exist an image for a given e-mail address
* in this case the `img` can be hidden via its `onerror` attribute

**Comment by jepsar** [comment]
Can you share what you have tried? I don't think the component should try and act on the response code.

**Comment by JensPiegsa** [comment]
**XHTML**:

```xml
<div class="avatar">
    <p:avatar shape="circle" styleClass="avatar-fallback" label="#{user.initials}" />
    <p:avatar shape="circle" styleClass="avatar-image">
        <p:graphicImage url="#{'https://www.gravatar.com/avatar/' += user.md5HashedMailAddress += '?d=404'}" 
                        pt:onerror="this.style.visibility='hidden'" />
    </p:avatar>
</div>
```

**CSS**:

```css
.avatar {
    position: relative;
}
.ui-avatar.avatar-fallback {
    border: 1px solid transparent;
    background-clip: content-box;
}
.ui-avatar.avatar-image {
    position: absolute;
    top: 0;
    left: 0;
}
```
