### ISSUE TITLE
TextEditor: Icons not showing up

### ISSUE THREAD

**Issue by MatthiasScherrerFGCZ** [primefaces/primefaces#8295]
Icons of the class ql-stroke are not showing up as --text-color is not defined and no fallback value is given.

![ql-stroke](https://user-images.githubusercontent.com/60141928/149761017-bf139678-0374-4e07-a376-eb7348ac93ff.png)

**xhtml**:
```xml
<p:textEditor
  id="message"
  required="true"
  height="600"
  styleClass="editWidthExtraHuge">
  <f:facet name="toolbar">
    <span class="ql-formats">
      <button class="ql-bold" />
      <button class="ql-header" value="1" />
      <button class="ql-header" value="2" />
    </span>
    <span class="ql-formats">
      <button class="ql-list" value="ordered" />
      <button class="ql-list" value="bullet" />
    </span>
    <span class="ql-formats">
      <button class="ql-link" />
    </span>
  </f:facet>
</p:textEditor>
```

**PF Version 11.0 (icons showing up)**
```css
.ql-snow .ql-stroke {
    fill: none;
    stroke: #444;
    stroke-linecap: round;
    stroke-linejoin: round;
    stroke-width: 2;
}
```

**PF Version 12.0 (icons not showing up)**
```css
.ql-snow .ql-stroke {
    fill: none;
    stroke: var(--text-color);
    stroke-linecap: round;
    stroke-linejoin: round;
    stroke-width: 2;
}
```

**Environment:**
 - PF Version: 12.0

Current workaround in our CSS:
```css
.ql-stroke {
    stroke: #444 !important;
}
```

**Comment by melloware** [comment]
Which theme are you using?

working fine for me in Arya, Saga and Vela.

![image](https://user-images.githubusercontent.com/4399574/149772585-12d91879-365a-4d2a-9366-8d563ef9450f.png)

![image](https://user-images.githubusercontent.com/4399574/149772635-90b29661-b664-4102-b40f-0eeb18ae4a7e.png)

**Comment by tuerker** [comment]
when theme is none, this problem appears.

**Comment by melloware** [comment]
Yes that would make sense its using the variable `var(--text-color);` to read the color from the theme so the font color and icon color is correct.

If you want theme = none then you need to add this to your CSS...

```css
:root {
    --text-color: #444;
}
```

or whatever you what your text color to be  PrimeTek has invested so much in the PrimeOne theme concept that trying to use 12.0 with legacy themes or no theme will become more and more difficult for you.

For example for Arya here are the variables exposed...

![image](https://user-images.githubusercontent.com/4399574/149775714-906b5681-c758-4073-8bab-e95945adce1c.png)
