### ISSUE TITLE
OrderList: Inconsitent padding for controlsLocation="right"

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#8541]
**Describe the defect**

Theming issue with inconsitent padding for `<p:orderList controlsLocation="right">`

![current](https://user-images.githubusercontent.com/21124034/157398238-bc41f208-f8ab-4111-b0c8-fa2921885c5d.png)

**Workaround**

Custom CSS

```css
body .ui-orderlist .ui-g > div.ui-orderlist-controls:not(:first-child) {
    padding: 0 0 0 0.5rem;
}
```
