### ISSUE TITLE
TabView/AccordionPanel/TextEditor: error indication theme styling

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8661]
**Description**
Based on issues: https://github.com/primefaces/primefaces/issues/8659 and  https://github.com/primefaces/primefaces/issues/8663

We need theme changes that generate styles for `ui-state-error` on Accordion /TabView/TextEditor similar to..

```css
body .ui-tabs.ui-tabs-top > .ui-tabs-nav li.ui-tabs-header.ui-state-error {
  border-color: red;
}

body .ui-accordion .ui-accordion-header.ui-state-error {
    border-color: red;
    background: lightpink;
    color: red;
}

body .ui-texteditor.ui-texteditor > .ql-container,
body .ui-texteditor.ui-texteditor > .ql-toolbar {
  border-color: red;
}
```

To make the UI look like...
![PF8659-Accordion](https://user-images.githubusercontent.com/4399574/162813842-ad8874a1-c53a-4afa-9b8b-2409e3a896a7.png)
![PF8659-Tab](https://user-images.githubusercontent.com/4399574/162813843-fcdf6ed2-2f35-4064-af17-68d3c872ea2f.png)

![image](https://user-images.githubusercontent.com/4399574/162963895-e7aeabe6-6786-45f5-9d25-77f1fc5dd64c.png)
