### ISSUE TITLE
DataTable: Error in styling with rowStyleClass

### ISSUE THREAD

**Issue by pstawik** [primefaces/primefaces#9079]
### Describe the bug

I tried to make changes in Primfaces Theme Designer on PF11. I added following code on home.xhtml

><ui:define name="content">
>        <style type="text/css">
>            .WE {
>           	background-color: #FFCCCC;
>            }
>        </style>
>        ...
>         <div class="card ui-fluid">
>                    <p:dataTable ... rowStyleClass="WE">
>                    ...

Of course, the style was not used for rows. This code works correctly on PF8.0.7. After adding the word "!important" to the style class .WE, the background color changed, but unfortunately there was no coloring of the rows for onMouseOver and onRowSelect events.

The attribute rowStyleClass is used in the [primefaces showcase ](https://www.primefaces.org/showcase/ui/data/datatable/rowColor.xhtml), but there is no styling of the onMouseOver and onRowSelect events. The PrimeTeak Team used "!important" in the style class, which - in my opinion - disabled coloring of the rows for onMouseOver and onRowSelect events.
I think that, this is a bug in PF11 and PF12. In the PF8 styling in that case works correctly.

### Expected behavior

When thw rowStyleClass is used in the dataTable component, the row styling of the onMouseOver and onRowSelect events should work properly.; the same behavior as in PF8.0.7. 

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.5

### Theme

Theme developed using Primefaces Theme Designer. 

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

Chrom, Firefox, Edge.

**Comment by tandraschko** [comment]
please provide a reproducer
there is of course no hover styling of the row in the showcase as no selection etc. is enabled

**Comment by jepsar** [comment]
See https://forum.primefaces.org/viewtopic.php?f=3&t=74729

You will need to override existing styling with greater specificity.

**Comment by pstawik** [comment]
> See https://forum.primefaces.org/viewtopic.php?f=3&t=74729
> 
> You will need to override existing styling with greater specificity.

It does not work ... Besides, the post is nice several years old, and the error appears in PF from version 11.
Please read my answer to your suggestion.

**Comment by pstawik** [comment]
I have provided reproducer.
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/9280868/primefaces-test-master.zip)

**Comment by jepsar** [comment]
Probably the "existing styling" changed between 8 and 11. You should find what the new existing rule for datatable row background is and override it with greater specificity.

That the linked post is several years old does not matter. The DOM inspector tool have not changed that much.

**Comment by jepsar** [comment]
These rules with greater specificity will work:
```css
body .ui-datatable .ui-datatable-data > tr.WE {
    background-color: #f67171;
}
body .ui-datatable .ui-datatable-data > tr.WY {
    background-color: #8be38b;
}
body .ui-datatable .ui-datatable-data > tr.WE.ui-state-hover {
    background-color: orange;
}
body .ui-datatable .ui-datatable-data > tr.WY.ui-state-hover {
    background-color: yellow;
}
```
