### ISSUE TITLE
ToggleSwitch: mark with 'ui-state-error' on failing validation 

### ISSUE THREAD

**Issue by mathezsolt11** [primefaces/primefaces#9161]
### Description

The p:toggleSwitch component doesn't get marked with the 'ui-state-error' styleClass, on failing validation, as other components do. It would be helpful to be able to identify the component easier as invalid, if validation fails.

Identified in primefaces version 11.0.5

### Describe the solution you would like

Add the 'ui-state-error' styleClass to the p:toggleSwitch, when the component is marked as invalid by the validation process.

**Comment by melloware** [comment]
OK this will still require  theme change

```css
body .ui-toggleswitch.ui-state-error {
    border: 1px solid #f44336;
}
```
