### ISSUE TITLE
ToggleSwitch: Theme ui-state-error

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#9165]
I fixed the main issue already:  https://github.com/primefaces/primefaces/pull/9162

Needs theme change something like..

```css
body .ui-toggleswitch.ui-state-error {
    border: 1px solid #f44336;
}
```
