### ISSUE TITLE
CommandButton: default button inline progress-indicator when execution action using PF 12

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#9296]
**1 Environment**

PrimeFaces version: primefaces 12.0.0
Application server: jetty 9.4.49 + version: mojarra-2.3

**2 Expected behavior**

By default the same Behavior as primefaces 11: no button progress-indicator.
Or an option to revert to the old behavior.

The "migration guide 11.0.0 -> 12.0.0" does not state anything about this.

Do like the new progress-indicator of commandButton but existing application already has a custom progress-indicator.
Also custom css styling for buttons is used.

**3 Actual behavior**

CommandButton default has a inline button progress-indicator when execution action.

**4 Steps to reproduce**

See sample project.

**5 Sample XHTML / Sample bean**

See attached project:
[primefaces-button.zip](https://github.com/primefaces/primefaces/files/9748037/primefaces-button.zip)

Primefaces 12:
primefaces-button.zip

run with:
mvn clean jetty:run -Pmojarra23

**Comment by melloware** [comment]
Isn't it this property ??

disableOnAjax | true | Boolean | If true, the button will be disabled during Ajax requests triggered by the button.
-- | -- | -- | --

**Comment by melloware** [comment]
And if you want to make that the default for all your CommandButtons in your app you can do so also: https://primefaces.github.io/primefaces/12_0_0/#/core/globalattributes

**Comment by DazzlingBob** [comment]
Tested with disableOnAjax="true" and disableOnAjax="false" but that does not work. Still a progress-indicator in the button.

**Comment by melloware** [comment]
cc @jepsar

**Comment by jepsar** [comment]
This was chosen as the default. You can use CSS to suppress it. (I can link the PR when I'm on my laptop). See the showcase for a custom CSS example.

**Comment by melloware** [comment]
Here is is:
```css
        html body .custom.ui-button.ui-button-text-only .ui-icon-loading {
            opacity: 0;
        }
        html body .custom.ui-button.ui-button-text-only .ui-icon-loading:before {
            content: "\e94a";
        }
        html body .custom.ui-button, html body .custom.ui-button * {
            transition-property: all;
            transition-duration: .2s;
        }
        html body .custom.ui-button.ui-state-loading {
            opacity: 1;
            background: #888;
            border-color: #888;
        }
        html body .custom.ui-button.ui-state-loading.ui-button-text-only .ui-button-text {
            opacity: 1;
            padding-left: 2rem;
        }
        html body .custom.ui-button.ui-state-loading.ui-button-text-only .ui-icon-loading {
            opacity: 1;
            left: 0;
            margin-left: 0.5rem;
        }
```

**Comment by melloware** [comment]
@DazzlingBob you should just be able to add
```css
html body .ui-button.ui-button-text-only .ui-icon-loading:before {
            content: "";
        }
```

To disable the icon from all buttons.

**Comment by DazzlingBob** [comment]
Thanks for the workaround/solution direction!
This css sadly does not recreate the old behaviour, the text of the button disappears on action.
You want to keep the button text and display it visually as active.

Like https://www.primefaces.org/showcase-v8/ui/button/commandButton.xhtml (cannot find showcase primefaces 11).
Will look at the difference in classes between 11 and 12 later on.

**Comment by jepsar** [comment]
Indeed, you will need different styling. I'll post the style to override the default behavior this evening.

**Comment by DazzlingBob** [comment]
Had a look at the generated classes:

PF11:
Button normal class:
ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only

Button with running action class:
ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-focus

PF12:
Button normal class:
ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only 

Button with running action class:
ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-loading ui-state-disabled

Added in PF12 are:
- disabled="disabled"
- extra span for the spinner

example:

```
<button
  class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only button ui-state-loading ui-state-disabled"
  disabled="disabled">
  <span class="ui-icon-loading ui-icon ui-c pi pi-spin pi-spinner"></span>
  <span class="ui-button-text ui-c">Save</span>
</button>
```

So one workaround is:
```
.ui-state-loading.ui-button-text-only .ui-icon-loading {
  display: none !important;
}
.ui-state-loading.ui-button-text-only .ui-icon-loading+.ui-button-text {
  opacity: inherit !important;
}
```

I do not like the !important, perhaps jepsar knows a better solution.

**Comment by jepsar** [comment]
If that's working for you, you could try
```css
html .ui-state-loading.ui-button-text-only .ui-icon-loading {
  display: none;
}
html .ui-state-loading.ui-button-text-only .ui-icon-loading+.ui-button-text {
  opacity: inherit;
}
```
I'll check this evening (CET).

**Comment by jepsar** [comment]
This is the issue and PR which include the motivation to make it default:

https://github.com/primefaces/primefaces/issues/8301

https://github.com/primefaces/primefaces/pull/8302

To override the CSS and suppress the load icon, use

```css
html .ui-state-loading.ui-button-text-only .ui-icon-loading + .ui-button-text {
    opacity: inherit;
}
html .ui-state-loading .ui-icon-loading {
    display: none;
}
html .ui-state-loading .ui-icon:not(.ui-icon-loading) {
    display: inherit;
}
```
