### ISSUE TITLE
FileUpload: custom icon attributes not working

### ISSUE THREAD

**Issue by doteo78** [primefaces/primefaces#9299]
### Describe the bug

Always default icons are displayed even when **chooseIcon**, **uploadIcon** and **cancelIcon** are specified.

### Reproducer

Run the attached project (mvn jetty:run) and visit http://localhost:8080/primefaces-test/.

### Expected behavior

In this test _pi-check_ icon should show in every button of the FileUpload component.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0 and 11.0.8

### JSF implementation

All
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/9754754/primefaces-test-master.zip)

### JSF version

2.2.x

### Java version

1.8

### Browser(s)

All

**Comment by jepsar** [comment]
@doteo78 Thanks! I'll have a look!

**Comment by melloware** [comment]
Its is because of the themes. The Themes override those custom icons.  To customize the icons you can do this...

```css
body .ui-fileupload .ui-fileupload-buttonbar .ui-button.ui-fileupload-choose .ui-icon:before {
    content: "\e909";
}
```

Attached is a fixed reproducer: 
[pf-9299.zip](https://github.com/primefaces/primefaces/files/9757450/pf-9299.zip)

**Comment by jepsar** [comment]
I think we should fix this in the component (set a default) and in the theme CSS.

**Comment by melloware** [comment]
Yep

**Comment by jepsar** [comment]
I'll add a PR which will set default PrimeIcons. @mertsincan to fully fix this you'll have to remove this style for the three buttons.
```css
body .ui-fileupload .ui-fileupload-buttonbar .ui-button.ui-fileupload-xxx .ui-icon:before {
    content: "x";
}
```
