### ISSUE TITLE
BreadCrumb: Home link not working with custom home icon

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#9311]
### Describe the bug

When using breadcrumb component configured with a custom home icon, like a FontAwesome icon, the home link is not working.

After some investigations it looks like there is no `<a>` markup as parent of the generated `<svg>` markup.

### Reproducer

[pf-breadcrumb-customicon.zip](https://github.com/primefaces/primefaces/files/9766142/pf-breadcrumb-customicon.zip)

### Expected behavior

Have the home link usable when using a custom home icon.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.0 and 13.0.0-SNAPSHOT

### Theme

Saga

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

All

**Comment by melloware** [comment]
Its similar to https://github.com/primefaces/primefaces/issues/9299

The theme.css is hard coding the icon:

```css
body .ui-breadcrumb .ui-breadcrumb-items li:first-child a.ui-icon-home:before {
    content: "\e925";
}
```

You need to override that CSS to be the icon you want for now.
