### ISSUE TITLE
Tree: Selectable nodes are not highlighted on hover

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#9315]
### Describe the bug

I think this is theme-only because `ui-state-hover` is added and removed correctly.

### Reproducer

[Showcase](https://www.primefaces.org/showcase/ui/data/tree/selection.xhtml?jfwid=0e559)

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

All

### JSF version

2

### Java version

11

**Comment by melloware** [comment]
@jepsar related to: https://github.com/primefaces/primefaces/issues/8649 ???

**Comment by jepsar** [comment]
It very well might. I'll have a look.

**Comment by jepsar** [comment]
Okay, so the class `ui-state-hover` **is** added to `div.ui-treenode-content.ui-tree-selectable`. The styling is missing / wrong.

Workaround:
```css
body .ui-tree .ui-tree-container .ui-treenode .ui-treenode-content.ui-state-hover {
    background: #e9ecef; /* depends on theme */
}
```
