### ISSUE TITLE
Chips: the value is truncated after about 20 characters

### ISSUE THREAD

**Issue by RegiK123** [primefaces/primefaces#9386]
### Describe the bug

the value is truncated after about 20 characters, but all put text should be visible without any wrapping
![image](https://user-images.githubusercontent.com/26834946/200590950-ffa37da0-c382-4000-a01b-20e30af782fb.png)

### Reproducer

![image](https://user-images.githubusercontent.com/26834946/200589147-a501a61c-7e6d-4228-b8f9-5ed5ba7e2cbc.png)

Go to ['...'](https://www.primefaces.org/showcase/ui/input/chips.xhtml?jfwid=39bf1)
Add new text that has more than 20 characters -> see attachment 

### Expected behavior

the value is truncated after about 20 characters, but all put text should be visible without any wrapping

### PrimeFaces version

12.0.0

### Theme

all

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

Chrome

**Comment by melloware** [comment]
Its this CSS causing it.

```css
.ui-chips-input-token {
   display: inline-flex;
}
```

You can workaround it with this CSS:

```css
body .ui-chips-input-token {
   display: inline;
}
```
