### ISSUE TITLE
Resizable: content does not grow

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#9390]
### Describe the bug

Which component should be resized?

https://www.primefaces.org/showcase/ui/misc/resizable.xhtml

### PrimeFaces version

12 showcase

### JSF implementation

All

### JSF version

n/a

### Java version

n/a

### Browser(s)

Chrome 107 | FF 106

**Comment by jepsar** [comment]
I do see a theme issue there. These rules solved it for me.

```css
.ui-resizable {
    display: flex;
    flex-direction: column;
}
.ui-resizable .ui-widget-content {
    flex-grow: 1;
}
```
