### ISSUE TITLE
DataTable: selectionMode=multiple with rowSelectMode=none still shows cursor pointer

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#9429]
### Describe the bug

DataTable Checkbox selection with `rowSelectMode="none"` still sets the `cursor: pointer` style on hover of the entire row, despite only being able to select via the Checkbox.

### Reproducer

This issue can be reproduced running the showcase locally. Modify the Checkbox example in the `ui/data/datatable/selection.xhtml` showcase page and set `rowSelectMode="none"`. Run the showcase and hover the rows in that example.

### Expected behavior

If a row cannot be selected by clicking on the row itself, the cursor should remain as the arrow rather than changing to a pointer.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

All

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

All

**Comment by melloware** [comment]
looks like its this in the themes.

```css
body .ui-datatable .ui-datatable-data>tr.ui-datatable-selectable {
    cursor: pointer;
}
```

**Comment by melloware** [comment]
Actually its this line...

```java
.add(allowSelection, DataTable.SELECTABLE_ROW_CLASS)
```

**Comment by melloware** [comment]
Workaround:
```css
body .ui-datatable .ui-datatable-data > tr.ui-datatable-selectable {
  cursor: auto;
}
```
