### ISSUE TITLE
ToggleSwitch: onIcon should be bound to onPosition

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9623]
### Describe the bug

Look at the example

https://www.primefaces.org/showcase/ui/input/toggleSwitch.xhtml?jfwid=5bc1c

with

`<p:toggleSwitch value="#{selectBooleanView.value2}" onIcon="pi pi-check" offIcon="pi pi-times" />`

Actually, the `onIcon` represents the _disabled_ state, and the `offIcon` represents the _enabled_ state. But it should be exactly the opposite, or? If the user disables the value, then it should have the `offIcon` and not the `onIcon` (and vice versa). 

According to the official doc:

> `onIcon`: The icon representing the "On" position.

But it actually represents the "Off" position.

> `offIcon`: The icon representing the "Off" position.

But it actually represents the "On" position.

### Expected behavior

> `onIcon`: The icon representing the "On" position.

It should represent the "On" position (as the documentation says).

> `offIcon`: The icon representing the "Off" position.

It should represent the "Off" position (as the documentation says).

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
You are right they do look backwards compared to what was intended: https://github.com/primefaces/primefaces/issues/7901

**Comment by melloware** [comment]
Here is a CSS workaround that fixes it.

```css
.ui-toggleswitch-dual-icon.ui-toggleswitch-checked .ui-toggleswitch-handler span + span {
  opacity: 0;
  transform: rotate(-90deg);
}

.ui-toggleswitch-dual-icon.ui-toggleswitch-checked .ui-toggleswitch-handler span {
  opacity: 1;
  transform: rotate(90deg);
}

.ui-toggleswitch-dual-icon .ui-toggleswitch-handler span + span {
  opacity: 1;
  transform: rotate(0deg);
}

.ui-toggleswitch-dual-icon .ui-toggleswitch-handler span {
  opacity: 0;
  transform: rotate(90deg);
}
```
