### ISSUE TITLE
DialogFramework: incorrect/missing icon for message severity INFO/FATAL (Theme).

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#9625]
### Describe the bug

Dialogs generated with `PrimeFaces.current().dialog().showMessageInDialog(message)` show incorrect/inconsistent icon (compared to growl and messages) for _SEVERITY_INFO_ and even no icon for _SEVERITY_FATAL_.

### Reproducer

[Showcase](https://www.primefaces.org/showcase/ui/df/message.xhtml?jfwid=4bd81)

Hit button and iterate through message icon classes with browser development tools:
- ui-messages-info-icon
- ui-messages-warn-icon
- ui-messages-error-icon
- ui-messages-fatal-icon

### Expected behavior

Compare with e.g. [Growl](https://www.primefaces.org/showcase/ui/message/growl.xhtml?jfwid=4bd81)

### PrimeFaces edition

None

### PrimeFaces version

12

### JSF implementation

All

### JSF version

2

### Java version

11

**Comment by irieill** [comment]
Is it possible to create theme related issues in a more simple way than the new issue form that requires versions and so on? Also is it possible to add theme lable myself?

**Comment by jepsar** [comment]
We've opted to make those fields required to try to keep PrimeNG / React / Vue issues out of here. Adding a form for theme issues (which is the only way to let everyone set that tag) seems overkill to me.

**Comment by melloware** [comment]
CSS workaround:
```css
body .ui-dialog.ui-message-dialog .ui-dialog-content>span.ui-dialog-message.ui-messages-info-icon:before {
    content: "\e924";
}

body .ui-dialog.ui-message-dialog .ui-dialog-content > span.ui-dialog-message.ui-messages-fatal-icon {
  font-family: "primeicons" !important;
  font-style: normal;
  font-weight: normal;
  display: inline-block;
  background: none;
}

body .ui-dialog.ui-message-dialog .ui-dialog-content>span.ui-dialog-message.ui-messages-fatal-icon:before {
    content: "\e910";
}
```
