### ISSUE TITLE
Tree:ContextMenu: Treeview is showing a I-beam cursor instead of mouse pointer

### ISSUE THREAD

**Issue by bjornerikolsen** [primefaces/primefaces#9826]
### Describe the bug

Noticed that when hovering over a treeview in PF 12 the mouse cursor changes to a I-beam cursor/pointer. Also when clicking on a treeview item. In PF 11 and before it's a normal mouse pointer, so this change happened in PF 12. This is the same for all the treeviews.

### Reproducer

It can be seen in the PF showcase, hover over the text in the treeview: [http://www.primefaces.org:8080/showcase/ui/data/tree/contextMenu.xhtml?jfwid=07aa5](url)

### Expected behavior

When hovering over and clicking on treeview items the cursor is a normal mouse cursor, not I-beam cursor.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.2

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Workaround until its fixed in 13.0.0

```css
body .ui-tree .ui-tree-container .ui-treenode .ui-treenode-content .ui-treenode-label {
   cursor: default;
}
```
