### ISSUE TITLE
Timeline: Upgrade to vis-timeline 7.7.0

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#9870]
Upgrade to vis-timeline 7.7.0

**Comment by amittel** [comment]
I am running on PrimeFaces 13.0.0-SNAPSHOT

I think the `<f:facet name="menu">` is not styled correctly.

It looks like the css for `div.timeline-menu ` is missing.

```
div.timeline-menu {
  position: absolute;
  right: 0;
  margin: 10px;
  z-index: 5;
}
```

Looking at the [PF12 showcase](https://www.primefaces.org/showcase/ui/data/timeline/custom.xhtml), the menu is at the right side in the timeline
![grafik](https://user-images.githubusercontent.com/822396/223669980-d456d205-fa22-4129-94ed-0d7f1412c180.png)

But the upgrade places the menu on the left side over the timeline
![grafik](https://user-images.githubusercontent.com/822396/223670380-5e15e390-37bd-4ee5-9295-64dd18173222.png)

**Comment by melloware** [comment]
Thanks I will take a look!  Let me know if you see any other CSS issue

**Comment by melloware** [comment]
weird its still in the timeline.css if you look in the browser.

```css
/**************************/
/** Custom PrimeFaces css */
/**************************/

div.timeline-menu {
	position: absolute;
	right: 0;
	margin: 10px;
	z-index: 5;
	/*it must be equals to vis-tooltip*/
}

div.timeline-menu-axis-both {
	top: 50px;
}

div.timeline-menu-axis-top {
	bottom: 0px;
}

div.timeline-menu-rtl {
	left: 0px;
	right: inherit;
}
```

But its definitely not taking effect.
