### ISSUE TITLE
Password: Eye icon problem in MS Edge and IE

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#9880]
See: https://stackoverflow.com/questions/75661945/primefaces-password-togglemask-two-togglers-for-edge-browser

PrimeReact already fixed this: https://github.com/primefaces/primereact/issues/3756

**Comment by melloware** [comment]
Same fix as used in other Prime libs:

```css
.ui-password::-ms-reveal,
.ui-password::-ms-clear {
    display: none;
}
```
