### ISSUE TITLE
SelectOneButton: Broken styles if max-width: 640px

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#9915]
### Describe the bug

The component style is broken if max-width is 640px. There is applied some ```@media``` rule.
```
@media (max-width: 640px)
body .ui-selectonebutton > div.ui-button:first-child, body .ui-selectmanybutton > div.ui-button:first-child {
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
@media (max-width: 640px)
body .ui-selectonebutton > div.ui-button:not(:last-child), body .ui-selectmanybutton > div.ui-button:not(:last-child) {
    border-bottom-width: 0;
    border-right-width: 1px;
}
```

### Reproducer

1. open [one button show case](https://www.primefaces.org/showcase/ui/input/oneButton.xhtml)
2. change window size less than 640px

### Expected behavior

the component is still displayed well

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0.

### JSF implementation

Mojarra

### JSF version

2.3.18

### Java version

11

### Browser(s)

Chromium 110.0.5481.100 (Official Build) snap (64-bit)

**Comment by melloware** [comment]
Going to mark this as Theme because its happening in the Theme SCSS.

```scss
@media (max-width: 640px) {
    .ui-selectonebutton > div.ui-button,
    .ui-selectmanybutton > div.ui-button {
      &:not(:last-child) {
        border-bottom-width: 0;
        border-right-width: 1px;
      }

      &:first-child {
        @include border-radius-top($borderRadius);
        @include border-radius-bottom(0);
      }

      &:last-child {
        @include border-radius-top(0);
        @include border-radius-bottom($borderRadius);
        border-bottom-width: 1px;
      }
    }
  }
```
