### ISSUE TITLE
TextEditor: toolbar difficult to see the toolbar with legacy theme

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#9920]
### Describe the bug

textEditor toolbar: it is difficult to see the toolbar (blue background) with nova-colored theme. 
Need a different toolbar background color for the theme.

https://www.primefaces.org/showcase/ui/input/textEditor.xhtml

Select theme "Nova Accent" that is actually "nova-colored".

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Nova Colored

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

11

### Browser(s)

Chrome 110

**Comment by jepsar** [comment]
It's a legacy theme, so I'm not expecting a fix. You could override styling in your project.

**Comment by melloware** [comment]
Agreed Legacy theme so no time  will be put into it.  CSS to work around the issue: 
```css
.ui-texteditor .ui-editor-toolbar.ql-snow .ql-stroke {
  stroke: white !important;
}
.ui-texteditor .ui-editor-toolbar.ql-snow .ql-picker .ql-picker-label {
  color: white !important;
}
.ui-texteditor .ui-editor-toolbar.ql-snow .ql-fill {
  fill: white !important;
}
```

**Comment by melloware** [comment]
Anyone still checking this thread i updated a legacy theme still using LESS and used this in the `theme.less` file

```css
.ui-texteditor .ui-editor-toolbar.ql-snow .ql-stroke {
  stroke: @tabview-tab-header-text-color !important;
}
.ui-texteditor .ui-editor-toolbar.ql-snow .ql-picker .ql-picker-label {
  color: @tabview-tab-header-text-color !important;
}
.ui-texteditor .ui-editor-toolbar.ql-snow .ql-fill {
  fill: @tabview-tab-header-text-color !important;
}
```
